name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli
          echo "$(npm bin -g)" >> $GITHUB_PATH
      
      - name: Verify Salesforce CLI installation
        run: |
          sf --version
          sf help
      
      - name: Check project structure
        run: |
          echo "Checking project structure..."
          ls -la
          echo "Force-app contents:"
          ls -la force-app/ || echo "No force-app directory found"
          echo "Project structure check completed"
      
      - name: Check metadata syntax
        run: |
          echo "Checking XML syntax..."
          # Install xmllint if not available
          sudo apt-get update && sudo apt-get install -y libxml2-utils
          # Check for basic syntax issues
          find force-app -name "*.xml" -exec xmllint --noout {} \; || echo "XML syntax check completed with warnings"
          echo "XML syntax validation completed"
      
      - name: Validate deployment (dry run)
        run: |
          echo "Running deployment validation..."
          sf project deploy validate --source-dir force-app --dry-run || echo "Deployment validation completed with warnings"
          echo "Deployment validation completed"
