name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli
          echo "$(npm bin -g)" >> $GITHUB_PATH
      
      - name: Verify Salesforce CLI installation
        run: |
          sf --version
          sf help
      
      - name: Validate project structure
        run: |
          sf project validate
          echo "Project structure validation completed"
      
      - name: Check metadata syntax
        run: |
          # Check for basic syntax issues
          find force-app -name "*.xml" -exec xmllint --noout {} \;
          echo "XML syntax validation completed"
      
      - name: Validate deployment (dry run)
        run: |
          sf project deploy validate --source-dir force-app --dry-run
          echo "Deployment validation completed"
