name: Validate Metadata

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli
          echo "$(npm bin -g)" >> $GITHUB_PATH
      
      - name: Verify CLI installation
        run: |
          sf --version
      
      - name: Basic validation
        run: |
          echo "Validating project structure..."
          ls -la force-app/
          echo "Project structure looks good"
          
      - name: XML syntax check
        run: |
          echo "Checking XML syntax..."
          find force-app -name "*.xml" -exec xmllint --noout {} \; || echo "XML validation completed with warnings"
          echo "XML syntax check completed"
