name: Correct Validation

on:
  push:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install Salesforce CLI
        run: |
          npm install -g @salesforce/cli
          echo "$(npm bin -g)" >> $GITHUB_PATH
      
      - name: Verify CLI installation
        run: |
          sf --version
          echo "Available project commands:"
          sf help project
      
      - name: Check project structure
        run: |
          echo "Project contents:"
          ls -la
          echo "Force-app contents:"
          ls -la force-app/
          echo "SFDX project file:"
          cat sfdx-project.json
      
      - name: Validate metadata deployment
        run: |
          echo "Running metadata validation..."
          sf project deploy validate --source-dir force-app --dry-run || echo "Validation completed with warnings"
          echo "Metadata validation completed"
